name: witchi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - numpy
  - joblib
  - seaborn
  - matplotlib
  - pytest
  - pip
  - git
  - pip:
    - pre-commit
    - git+https://github.com/stephkoest/witchi
