name: witchi-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - biopython
  - joblib
  - seaborn
  - matplotlib
  - gnuplot
  - pip:
     - "--editable=git+https://github.com/dkogan/gnuplotlib.git#egg=gnuplotlib"