name: CI

on: [push, pull_request]

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run tests
        run: |
          export PYTHONPATH=src
          pytest tests/
